#!/bin/sh
if [ $# -eq 0 ]
then
juliapath=julia
else
juliapath=$1
fi

$juliapath -e '"Documenter" in keys(Pkg.installed()) || Pkg.add("Documenter");'
$juliapath -e '"PyPlot" in keys(Pkg.installed()) || Pkg.add("PyPlot");'

$juliapath make.jl

mkdocs build --clean
